import { ITemplateArmor } from './game-data.model';

export const ARMOR_DATA: ITemplateArmor[] = [
  {
    id: 'clothes',
    type: 'armor',
    name: 'Clothes',
    level: 1,
    icon: 'clothes.png',
    defense: 1,
    weight: 2,
    value: 10,
    usedby: [],
    groups: ['default'],
  },
  {
    id: 'cloak',
    type: 'armor',
    name: 'Cloak',
    level: 1,
    icon: 'cloak.png',
    defense: 1,
    weight: 2,
    value: 10,
    usedby: ['mage', 'healer'],
    groups: ['default'],
  },
  {
    id: 'leather-helm',
    type: 'helm',
    name: 'Leather Helm',
    level: 1,
    icon: 'leatherHelm.png',
    defense: 1,
    weight: 1,
    value: 75,
    usedby: ['warrior', 'ranger'],
    groups: ['default'],
  },
  {
    id: 'leather-boots',
    type: 'boots',
    name: 'Leather Boots',
    level: 1,
    icon: 'leatherBoots2.png',
    defense: 1,
    weight: 1,
    value: 60,
    usedby: ['warrior', 'ranger'],
    groups: ['default'],
  },
  {
    id: 'leather-shield',
    type: 'shield',
    name: 'Leather Shield',
    level: 1,
    icon: 'leatherShield.png',
    defense: 2,
    weight: 2,
    value: 40,
    usedby: ['warrior'],
    groups: ['rare'],
  },
  {
    id: 'leather-armor',
    type: 'armor',
    name: 'Leather Armor',
    level: 1,
    icon: 'leatherArmor.png',
    defense: 4,
    weight: 8,
    value: 150,
    usedby: ['warrior', 'ranger'],
    groups: ['default'],
  },
  {
    id: 'apprentice-hat',
    type: 'helm',
    name: 'Apprentice Hat',
    level: 1,
    icon: 'wizardHat1.png',
    defense: 1,
    weight: 1,
    value: 150,
    usedby: ['mage', 'healer'],
    groups: ['rare'],
  },
  {
    id: 'coral-helm',
    type: 'helm',
    name: 'Coral Helm',
    level: 2,
    icon: 'coralHelm.png',
    defense: 2,
    weight: 1,
    value: 175,
    usedby: ['warrior', 'ranger'],
    groups: ['magic', 'default'],
    elements: ['water'],
  },
  {
    id: 'iron-shield',
    type: 'shield',
    name: 'Iron Shield',
    level: 2,
    icon: 'ironShield.png',
    defense: 5,
    weight: 8,
    value: 200,
    usedby: ['warrior'],
    groups: ['default'],
  },
  {
    id: 'studded-armor',
    type: 'armor',
    name: 'Studded Armor',
    level: 2,
    icon: 'studdedArmor.png',
    defense: 8,
    weight: 10,
    value: 250,
    usedby: ['warrior', 'ranger'],
    groups: ['default'],
  },
  {
    id: 'chain-mail-armor',
    type: 'armor',
    name: 'Chain Mail Armor',
    level: 3,
    icon: 'equipArmor.png',
    defense: 10,
    weight: 15,
    value: 450,
    usedby: ['warrior'],
    groups: ['default'],
  },
  {
    id: 'merman-shield',
    type: 'shield',
    name: 'Merman Shield',
    level: 3,
    icon: 'mermanShield.png',
    defense: 4,
    weight: 2,
    value: 500,
    usedby: ['warrior'],
    groups: ['magic', 'default'],
    elements: ['water'],
  },
  {
    id: 'elvish-cloak',
    type: 'armor',
    name: 'Elvish Cloak',
    level: 2,
    icon: 'elvishCloak.png',
    defense: 6,
    weight: 2,
    value: 200,
    usedby: ['mage', 'healer'],
    groups: ['default'],
  },
  {
    id: 'seaweed-armor',
    type: 'armor',
    name: 'Seaweed Armor',
    level: 3,
    icon: 'seaweedArmor.png',
    defense: 10,
    weight: 5,
    value: 600,
    usedby: ['warrior', 'ranger'],
    groups: ['magic', 'default'],
    elements: ['water'],
  },
];

/** Get an armor descriptor given its id value */
export function getArmorById(id: string): ITemplateArmor | null {
  return ARMOR_DATA.find((item) => item.id === id) || null;
}
