import { ITemplateWeapon } from '../game-data.model';

export const WEAPONS_DATA: ITemplateWeapon[] = [
  {
    id: 'club',
    type: 'weapon',
    name: 'Club',
    level: 1,
    icon: 'club.png',
    attack: 5,
    hit: 2,
    value: 25,
    usedby: ['warrior'],
    groups: ['default'],
  },
  {
    id: 'slingshot',
    type: 'weapon',
    name: 'Slingshot',
    level: 1,
    icon: 'sling.png',
    attack: 5,
    hit: 10,
    value: 25,
    usedby: ['ranger'],
    groups: ['default'],
  },
  {
    id: 'short-sword',
    type: 'weapon',
    name: 'Short Sword',
    level: 1,
    icon: 'shortSword.png',
    attack: 9,
    hit: 7,
    value: 350,
    usedby: ['warrior', 'ranger'],
    groups: ['default'],
  },
  {
    id: 'short-staff',
    type: 'weapon',
    name: 'Short Staff',
    level: 1,
    icon: 'shortStaff.png',
    attack: 6,
    hit: 0,
    value: 25,
    usedby: ['mage', 'healer'],
    groups: ['default'],
  },
  {
    id: 'kobold-staff',
    type: 'weapon',
    name: 'Kobold Staff',
    level: 2,
    icon: 'staff2.png',
    attack: 8,
    hit: 0,
    value: 250,
    usedby: ['mage', 'healer'],
    groups: ['rare'],
  },
  {
    id: 'scimitar',
    type: 'weapon',
    name: 'Scimitar',
    level: 1,
    icon: 'scimitar.png',
    attack: 8,
    hit: 10,
    value: 200,
    usedby: ['warrior', 'ranger'],
    groups: ['rare'],
  },
  {
    id: 'short-bow',
    type: 'weapon',
    name: 'Short Bow',
    level: 1,
    icon: 'shortBow2.png',
    attack: 7,
    hit: 15,
    value: 250,
    usedby: ['ranger'],
    groups: ['default'],
  },
  {
    id: 'goblin-crossbow',
    type: 'weapon',
    name: 'Goblin Crossbow',
    level: 1,
    icon: 'crossbow3.png',
    attack: 8,
    hit: 5,
    value: 300,
    usedby: ['ranger'],
    groups: ['rare'],
  },
  {
    id: 'long-sword',
    type: 'weapon',
    name: 'Long Sword',
    level: 2,
    icon: 'equipWeapon.png',
    attack: 15,
    hit: 5,
    value: 500,
    usedby: ['warrior'],
    groups: ['default'],
  },
  {
    id: 'long-bow',
    type: 'weapon',
    name: 'Long Bow',
    level: 2,
    icon: 'bow.png',
    attack: 11,
    hit: 15,
    value: 500,
    usedby: ['ranger'],
    groups: ['default'],
  },
  {
    id: 'long-staff',
    type: 'weapon',
    name: 'Long Staff',
    level: 2,
    icon: 'staff.png',
    attack: 4,
    hit: 12,
    value: 150,
    usedby: ['mage', 'healer'],
    groups: ['default'],
  },
  {
    id: 'magic-sword',
    type: 'weapon',
    name: 'Magic Sword',
    level: 3,
    icon: 'magicSword.png',
    attack: 17,
    hit: 20,
    value: 750,
    usedby: ['warrior'],
    groups: ['default', 'rare'],
    elements: ['holy'],
  },
  {
    id: 'broadsword',
    type: 'weapon',
    name: 'Broadsword',
    level: 3,
    icon: 'sword2.png',
    attack: 21,
    hit: 0,
    value: 600,
    usedby: ['warrior'],
    groups: ['default'],
  },
  {
    id: 'heavy-axe',
    type: 'weapon',
    name: 'Heavy Axe',
    level: 3,
    icon: 'axe2.png',
    attack: 19,
    hit: 0,
    value: 500,
    usedby: ['warrior'],
    groups: ['default'],
  },
  {
    id: 'fine-bow',
    type: 'weapon',
    name: 'Fine Bow',
    level: 3,
    icon: 'shortBow.png',
    attack: 13,
    hit: 17,
    value: 500,
    usedby: ['ranger'],
    groups: ['default'],
  },
  {
    id: 'heavy-crossbow',
    type: 'weapon',
    name: 'Heavy Crossbow',
    level: 3,
    icon: 'crossbow2.png',
    attack: 15,
    hit: 7,
    value: 600,
    usedby: ['ranger'],
    groups: ['default'],
  },
  {
    id: 'long-oak-staff',
    type: 'weapon',
    name: 'Long Oak Staff',
    level: 3,
    icon: 'hookedStaff.png',
    attack: 10,
    hit: 18,
    value: 550,
    usedby: ['mage', 'healer'],
    groups: ['default'],
  },
  {
    id: 'coral-staff',
    type: 'weapon',
    name: 'Coral Staff',
    level: 3,
    icon: 'coralStaff.png',
    attack: 11,
    hit: 20,
    value: 800,
    usedby: ['mage', 'healer'],
    groups: ['default'],
    elements: ['water'],
  },
  {
    id: 'narwhal-sword',
    type: 'weapon',
    name: 'Narwhal Sword',
    level: 3,
    icon: 'coralSword.png',
    attack: 16,
    hit: 22,
    value: 1000,
    usedby: ['warrior'],
    groups: ['rare'],
    elements: ['water'],
  },
];
