import { ITemplateEnemy } from '../game-data.model';

export const ENEMIES_DATA: ITemplateEnemy[] = [
  {
    id: 'snake',
    name: 'Snake',
    level: 1,
    icon: 'greensnake.png',
    exp: 8,
    gold: 6,
    hp: 18,
    mp: 0,
    attack: 6,
    defense: 6,
    hitpercent: 12,
  },
  {
    id: 'imp',
    name: 'Imp',
    level: 1,
    icon: 'imp.png',
    exp: 6,
    gold: 3,
    hp: 6,
    mp: 0,
    attack: 4,
    defense: 3,
    hitpercent: 11,
  },
  {
    id: 'huge-spider',
    name: 'Huge Spider',
    level: 2,
    icon: 'hugeSpider.png',
    exp: 12,
    gold: 20,
    hp: 30,
    mp: 0,
    attack: 12,
    defense: 3,
    hitpercent: 12,
  },
  {
    id: 'kobold',
    name: 'Kobold',
    level: 2,
    icon: 'kobold.png',
    exp: 7,
    gold: 15,
    hp: 24,
    mp: 0,
    attack: 8,
    defense: 6,
    hitpercent: 15,
  },
  {
    id: 'kobold-fighter',
    name: 'Kobold Fighter',
    level: 2,
    icon: 'koboldSwordsman.png',
    exp: 15,
    gold: 0,
    hp: 45,
    mp: 0,
    attack: 15,
    defense: 9,
    hitpercent: 20,
  },
  {
    id: 'kobold-shaman',
    name: 'Kobold Shaman',
    level: 3,
    icon: 'koboldShaman.png',
    exp: 50,
    gold: 20,
    hp: 65,
    mp: 0,
    attack: 12,
    defense: 18,
    hitpercent: 50,
  },
  {
    id: 'black-spider',
    name: 'Black Spider',
    level: 3,
    icon: 'blackSpider.png',
    exp: 15,
    gold: 10,
    hp: 18,
    mp: 0,
    attack: 17,
    defense: 11,
    hitpercent: 26,
  },
  {
    id: 'ice-troll',
    name: 'Ice Troll',
    level: 4,
    icon: 'iceTroll.png',
    exp: 50,
    gold: 100,
    hp: 80,
    mp: 0,
    attack: 30,
    defense: 9,
    hitpercent: 52,
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    level: 3,
    icon: 'skeleton.png',
    exp: 12,
    gold: 20,
    hp: 15,
    mp: 0,
    attack: 12,
    defense: 6,
    hitpercent: 20,
  },
  {
    id: 'goblin-scout',
    name: 'Goblin Scout',
    level: 1,
    icon: 'goblinScout.png',
    exp: 3,
    gold: 2,
    hp: 7,
    mp: 0,
    attack: 2,
    defense: 5,
    hitpercent: 11,
  },
  {
    id: 'goblin',
    name: 'Goblin',
    level: 2,
    icon: 'goblin.png',
    exp: 6,
    gold: 10,
    hp: 25,
    mp: 0,
    attack: 10,
    defense: 4,
    hitpercent: 20,
  },
  {
    id: 'goblin-spear',
    name: 'Goblin Grunt',
    level: 2,
    icon: 'goblin4.png',
    exp: 7,
    gold: 8,
    hp: 18,
    mp: 0,
    attack: 12,
    defense: 2,
    hitpercent: 12,
  },
  {
    id: 'goblin-archer',
    name: 'Goblin Archer',
    level: 2,
    icon: 'goblinArcher.png',
    exp: 5,
    gold: 11,
    hp: 20,
    mp: 0,
    attack: 9,
    defense: 2,
    hitpercent: 25,
  },
  {
    id: 'goblin-scimitar',
    name: 'Goblin Cutter',
    level: 2,
    icon: 'goblin6.png',
    exp: 25,
    gold: 15,
    hp: 24,
    mp: 0,
    attack: 15,
    defense: 4,
    hitpercent: 20,
  },
  {
    id: 'goblin-shield-axe',
    name: 'Goblin Armor',
    level: 3,
    icon: 'goblin7.png',
    exp: 30,
    gold: 25,
    hp: 32,
    mp: 0,
    attack: 16,
    defense: 0,
    hitpercent: 8,
  },
  {
    id: 'goblin-king',
    name: 'Goblin King',
    level: 5,
    icon: 'goblinKing.png',
    exp: 150,
    gold: 200,
    hp: 150,
    mp: 100,
    attack: 25,
    defense: 10,
    hitpercent: 20,
  },
  {
    id: 'goblin-wizard',
    name: 'Goblin Wizard',
    level: 3,
    icon: 'goblinWizard.png',
    exp: 35,
    gold: 25,
    hp: 48,
    mp: 50,
    attack: 24,
    defense: 8,
    hitpercent: 20,
  },
];
